[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
sea-orm = "1.1.4"
serde = { version = "1.0.217", features = ["derive"] }
uuid = "1.13.1"